### ISSUE TITLE
Customizing background color of fireworks preset results in flashing color before fading to black

### ISSUE THREAD

**Issue by meneman** [tsparticles/tsparticles#4638] opened 2022-08-19 11:22 UTC
### Contact Details

ja.steege@gmail.com

### What do you need?

Hello,
i tried to costomize the background of the tsparticles-preset-fireworks preset. I wen`t about it as following:

```
        <Particles options={{
          preset: "fireworks",
          fullScreen: false,
          background: { color: "#ffff" }
        }} id="tsparticles" />
```

This results into the background being white for a moment and than fading to black. From my understanding of the following text from the presets github page, changing the background color should be possible:

> Important ⚠️ You can override all the options defining the properties like in any standard tsParticles installation.

What did i do wrong? Is there another way to fix this problem?

Thanks in advance.

### tsParticles Version

2.2.2

### Which library are you using?

React.js (react-particles, react-tsparticles, react-particles-js)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment] 2022-08-19 11:53
Duplicate of #3495

**Closed as completed by matteobruni** 2022-08-19 11:53 UTC
Labels: triage
