### ISSUE TITLE
Cannot find module 'tsparticles' or its corresponding type declarations.

### ISSUE THREAD

**Issue by madmacc** [tsparticles/tsparticles#4811] opened 2022-11-09 03:42 UTC
### Contact Details

wekasolutions@gmail.com

### What happened?

I get the following errors:
Error: Module not found: Error: Can't resolve 'tsparticles' in 'apppath'       
error TS2307: Cannot find module 'tsparticles' or its corresponding type declarations.

Same issue as https://github.com/matteobruni/tsparticles/issues/1683

import { MoveDirection, ClickMode, HoverMode, OutMode, Engine, Container } from "tsparticles-engine";
import { loadFull } from "tsparticles";

"typescript": "~4.7.2"
"@angular/core": "^14.2.0",

### tsParticles Version

2.5.2

### Which library are you using?

Angular (ng-particles)

### tsParticles Configuration

```json
/* or the classic JavaScript object */
  particlesOptions = {
      background: {
          color: {
              value: "#0d47a1",
          },
      },
      fpsLimit: 120,
      interactivity: {
          events: {
              onClick: {
                  enable: true,
                  mode: ClickMode.push,
              },
              onHover: {
                  enable: true,
                  mode: HoverMode.repulse,
              },
              resize: true,
          },
          modes: {
              push: {
                  quantity: 4,
              },
              repulse: {
                  distance: 200,
                  duration: 0.4,
              },
          },
      },
      particles: {
          color: {
              value: "#ffffff",
          },
          links: {
              color: "#ffffff",
              distance: 150,
              enable: true,
              opacity: 0.5,
              width: 1,
          },
          collisions: {
              enable: true,
          },
          move: {
              direction: MoveDirection.none,
              enable: true,
              outModes: {
                  default: OutMode.bounce,
              },
              random: false,
              speed: 6,
              straight: false,
          },
          number: {
              density: {
                  enable: true,
                  area: 800,
              },
              value: 80,
          },
          opacity: {
              value: 0.5,
          },
          shape: {
              type: "circle",
          },
          size: {
              value: { min: 1, max: 5 },
          },
      },
      detectRetina: true,
  };
```

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
./src/app/pages/confirmation/confirmation.component.ts:2:0-39 - Error: Module not found: Error: Can't resolve 'tsparticles' in 'R:\hivepass\donate_hivepass_app\src\app\pages\confirmation'       

Error: src/app/pages/confirmation/confirmation.component.ts:3:26 - error TS2307: Cannot find module 'tsparticles' or its corresponding type declarations.

3 import { loadFull } from "tsparticles";
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment] 2022-11-09 06:02
Duplicate of #4784

**Closed as not planned by matteobruni** 2022-11-09 06:02 UTC
Labels: invalid, no-issue-activity
