### ISSUE TITLE
Particles to have a soft collision option (with a radius)

### ISSUE THREAD

**Issue by mattjis** [tsparticles/tsparticles#1070] opened 2020-11-27 08:00 UTC
**Which version are you using?**
1.18.11

**Is the latest version affected?**

- [x] Yes
- [ ] No

**Which library are you using?**

- [ ] Vanilla JS (`tsparticles`)
- [x] React (`react-tsparticles`)
- [ ] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

**Is your feature request related to a problem? Please describe.**
This is what I'm going for: 
![IMG_1255](https://user-images.githubusercontent.com/21289982/100424843-214a2880-30c9-11eb-8e29-c883748fadbf.PNG)

And this is how it's currently looking (it's random, but you get the idea): 
![IMG_1257](https://user-images.githubusercontent.com/21289982/100424904-3cb53380-30c9-11eb-88a9-8241eaeb13e5.PNG)

**Describe the solution you'd like**
I want the particles to be a bit more spread out. Avoid clumping, or all being on one side etc..

**Comment by mattjis** [comment] 2020-11-27 08:01
Maybe some sort of soft collisions that have a large padding around the particle? I'm not sure how to achieve this.

**Comment by matteobruni** [comment] 2020-11-27 08:20
Hi @mattjis,

Sorry but I don't understand what are you are requesting, can you tell me more?

**Comment by mattjis** [comment] 2020-11-27 08:27
@matteobruni In the first image example, all of the particles are nicely spread out - this was made in adobe illustrator, and is how I ideally want the particles rendered (at least initially).

The second example image is my actual website using tsparticles. As you can see they're mostly on the right side, and a bunch of them are clumped up in a group. It's not very "aesthetically pleasing".

I basically want even(ish) spacing between all of the particles.

**Comment by mattjis** [comment] 2020-11-27 08:30
At the moment maybe 1/10 initial renders are nicely spread out. Which is of course, by chance.

**Comment by matteobruni** [comment] 2020-11-27 08:34
You can use the `manualParticles` property to give them a custom initial position.

You can see a sample config [here](https://github.com/matteobruni/tsparticles/blob/master/demo/main/public/presets/manual.json)

The initial position coordinates have percent values to adapt to all screen sizes.

**Comment by mattjis** [comment] 2020-11-27 08:38
@matteobruni Okay yeah I thought that may have be an option.

The thing is I'd have to set many of these manual configurations depending on the screen size, as I'd like the density to stay relatively the same.

And the move animation will still end up less than ideal over time

**Comment by mattjis** [comment] 2020-11-27 08:41
My problem is probably pretty niche. Appreciate your help though! @matteobruni 

You can close this if it's quite a difficult task.

**Comment by mattjis** [comment] 2020-11-27 08:44
"Soft collisions" is my feature request. So they never bang in to each other, but just move away from each slowly if they're within a radius. 

This would solve my issue, along with the other one I opened earlier about not spawning within the collision zone.

**Comment by matteobruni** [comment] 2020-11-27 08:47
In the upcoming `1.19.0` release there's a repulse radius feature around particles (issue #609), maybe it's what you're requesting, isn't it?

**Comment by mattjis** [comment] 2020-11-27 08:50
@matteobruni Yes I think so! That sounds pretty good.

**Comment by matteobruni** [comment] 2020-11-27 08:51
Ok so I can close this since it's a duplicate of #609

**Closed as completed by matteobruni** 2020-11-27 08:51 UTC
Labels: duplicate

**Comment by mattjis** [comment] 2020-11-27 08:53
Is there a way I can test the upcoming 1.19.0 on my react project, to see how this feature works?
Or will I have to wait until it's officially released?

**Comment by matteobruni** [comment] 2020-11-27 08:55
You can test it using the alpha/beta releases, since they are not officially released I don't care about breaking changes so errors can occur in a newer alpha/beta

**Comment by mattjis** [comment] 2020-11-27 08:56
@matteobruni Great, thanks for all your help! Love the project
