### ISSUE TITLE
[Bug]: Particle speed increasing over time when collisions is enabled

### ISSUE THREAD

**Issue by Dysrhythmic** [tsparticles/tsparticles#2586] opened 2021-11-24 21:06 UTC
### What happened?

I copied the configuration settings from [the npmjs page](https://www.npmjs.com/package/react-tsparticles) under "Options object" and noticed the particle movement speed increases more and more over time. I removed the following "collisions" configuration and it no longer has this issue.
```
collisions: {
  enable: true,
}
```

### Version

1.37.4

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### tsParticles Configuration

```
const particlesOptions = {
  fpsLimit: 60,
  interactivity: {
    events: {
      onClick: {
        enable: true,
        mode: "push",
      },
      onHover: {
        enable: true,
        mode: "repulse",
      },
      resize: true,
    },
    modes: {
      bubble: {
        distance: 400,
        duration: 2,
        opacity: 0.8,
        size: 40,
      },
      push: {
        quantity: 4,
      },
      repulse: {
        distance: 200,
        duration: 0.4,
      },
    },
  },
  particles: {
    color: {
      value: "#ffffff",
    },
    links: {
      color: "#ffffff",
      distance: 150,
      enable: true,
      opacity: 0.5,
      width: 1,
    },
    collisions: {
      enable: true,
    },
    move: {
      direction: "none",
      enable: true,
      outMode: "bounce",
      random: false,
      speed: 6,
      straight: false,
    },
    number: {
      density: {
        enable: true,
        value_area: 800,
      },
      value: 80,
    },
    opacity: {
      value: 0.5,
    },
    shape: {
      type: "circle",
    },
    size: {
      random: true,
      value: 5,
    },
  },
  detectRetina: true,
}
```

```
<Particles
  className='particles'
  id="tsparticles"
  init={particlesInit}
  loaded={particlesLoaded}
  options={particlesOptions}
/>
```
```


### What browsers are you seeing the problem on?

Firefox

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment] 2021-11-24 21:30
Duplicate of #2380

**Closed as completed** 2021-11-24 21:30 UTC
Labels: bug, triage
