### ISSUE TITLE
[Bug]: Background cannot be overwritten for fireworks preset

### ISSUE THREAD

**Issue by stevendecock** [tsparticles/tsparticles#5032] opened 2023-06-29 09:26 UTC
### Contact Details

decocksteven79@gmail.com

### What happened?

We are trying to use the fireworks preset, but would like to override the background.  It is now black and we would like it transparent.

We tried the following code (while including this bundle: https://cdn.jsdelivr.net/npm/tsparticles-preset-fireworks@2.10.0/tsparticles.preset.fireworks.bundle.js):

```
async function loadParticles(options) {
  await loadFireworksPreset(tsParticles);

  await tsParticles.load(options);
}

const configs = { preset: "fireworks", background: { color: "transparent"} };


loadParticles(configs);
```

We get the fireworks, but the background remains black.

### tsParticles Version

2.10.0

### tsParticles Configuration

```json
{ preset: "fireworks", background: { color: "transparent"} };
```

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment] 2023-06-29 09:43
Duplicate of #4882, #4576, #3495, #3078, #4870, #2446

**Closed as not planned by matteobruni** 2023-06-29 09:43 UTC
Labels: bug, triage
