### ISSUE TITLE
Polygon Mask Inside Particles Become Stuck

### ISSUE THREAD

**Issue by FraserHamilton** [tsparticles/tsparticles#1269] opened 2021-01-30 14:30 UTC
**Which version are you using?**
1.18.0

**Is the latest version affected?**

- [X] Yes
- [ ] No

**Which library are you using?**

- [ ] Vanilla JS (`tsparticles`)
- [X] React (`react-tsparticles`)
- [ ] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

**Describe the bug**
Particles can become stuck to the path and even sometimes escape beyond the path becoming trapped on the outside of it

**To Reproduce**
1. Add SVG Polygon Mask to config
2. Configure to contain particles inside of path

**Expected behavior**
Particles should bounce off the path smoothly and not become stuck and / or escape the path

**Screenshots**
https://i.gyazo.com/94a01938a9b6cf85fb0e496dcc4a5ee6.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 88

**Additional context**
This issue is even more noticeable when using symbols instead of circle shapes.

**Comment by FraserHamilton** [comment] 2021-01-30 14:33
Here's my conifg

```
{
        background: {
              color: {
                value: "#4950BA",
              },
            },
            detectRetina: false,
            interactivity: {
              events: {
                onHover: {
                  enable: true,
                  mode: "bubble",
                },
              },
              modes: {
                bounce: {
                  distance: 200,
                },
                bubble: {
                  distance: 40,
                  duration: 2,
                  opacity: 8,
                  size: 0,
                },
              },
            },
            particles: {
              color: {
                value: "#ffffff",
              },
              links: {
                color: {
                  value: "#ffffff",
                },
                distance: 50,
                enable: false,
                opacity: 0.4,
                width: 2,
              },
              collisions: {
                enable: false,
              },
              move: {
                direction: "none",
                enable: true,
                outMode: "bounce",
                random: false,
                speed: 2,
                straight: false,
              },
              number: {
                density: {
                  area: 500,
                },
                value: 50,
              },
              opacity: {
                value: 0.4,
                animation: {
                  enable: false,
                  minimumValue: 0.05,
                },
              },
              shape: {
                options: {
                  char: {
                    value: [
                      "a",
                      "b",
                      "c",
                      "d",
                      "e",
                      "f",
                      "g",
                      "h",
                      "i",
                      "j",
                      "k",
                      "l",
                      "m",
                      "n",
                      "o",
                      "p",
                      "q",
                      "r",
                      "s",
                      "t",
                      "u",
                      "v",
                      "w",
                      "x",
                      "y",
                      "z",
                    ],
                    font: "Roboto Mono",
                    style: "",
                    weight: "400",
                    fill: true,
                  },
                },
                type: "circle",
              },
              size: {
                random: false,
                value: 10,
              },
              stroke: {
                color: {
                  value: "#fffff",
                },
              },
            },
            polygon: {
              draw: {
                enable: true,
                stroke: {
                  color: {
                    value: "rgba(255,255,255,0.2)",
                  },
                  width: 5,
                  opacity: 0.2,
                },
              },
              enable: true,
              inline: {
                arrangement: "equidistant",
              },
              scale: 1,
              type: "inside",
              url: "http://localhost:3000/user-head.svg",
            },
}
```

**Comment by matteobruni** [comment] 2021-01-30 19:24
Thanks for reporting that, I noticed it some days ago and I'm working on it for the upcoming `2.0.0` release

**Comment by FraserHamilton** [comment] 2021-01-30 22:13
Excellent, just wasn't sure if I was configuring it wrong. I've also noticed particles not getting stuck but vibrating in a similiar manner when using the inline mask configuration, presumably this is a releated issue.

**Comment by matteobruni** [comment] 2021-01-30 22:15
Yes, they vibrate because they start bouncing forever. 

I'm adding a flag to make the bounce happen again only when the particles will be back in place. The issue is in the polygon mask plugin because it overrides the general bounce

**Comment by motion-work** [comment] 2021-04-14 08:43
@FraserHamilton how did you set the configuration so that your particles move inside the svg freely? in my version the particles just move onthe svg path: [https://res.cloudinary.com/delicious-cookie/video/upload/v1618389489/kaleido/Screen_Recording_2021-04-14_at_10.35.06_okxowj.mov](https://res.cloudinary.com/delicious-cookie/video/upload/v1618389489/kaleido/Screen_Recording_2021-04-14_at_10.35.06_okxowj.mov)

**Comment by matteoums** [comment] 2021-04-15 10:14
This issue is similar to #1256

**Comment by motion-work** [comment] 2021-05-05 14:04
Is there a possibility to try a fixed version already?

**Comment by matteobruni** [comment] 2021-05-05 14:07
Hi @motion-work, actually is not possible, the new bounce works fine but sometimes particles will go outside. When this bug is fixed I’ll release the new version.

**Comment by motion-work** [comment] 2021-05-05 14:20
thanks for the quick responsive. looking forward to it! Do you have an estimated release date?

**Comment by matteobruni** [comment] 2021-05-05 14:24
I hope to release it in some days, I just need to find the formula for adjusting particles that went outside instead of bouncing and it’s done.

**Comment by matteobruni** [comment] 2021-05-06 06:35
I created a PR with a first "working" version, some improvements can still be done but at least particles stays inside/outside correctly.
You can clone the `v1` branch to see how the new fixes appear.
To run the `main/demo` project you have to: 

- Execute `yarn && npx lerna bootstrap && npx lerna run build` inside the cloned folder
- Move to folder `main/demo`
- Execute `yarn start`
- Go to http://localhost:3000
- Search the `local polygon mask` sample in the dropdown
- You should see a triangle with particles bouncing inside

**Comment by motion-work** [comment] 2021-05-10 10:10
We really appreciate your effort on this issue. Do you think the `v1` branch can be merged into `main`  by tomorrow? We are going to release our website on Wednesday, it would be awesome to have this bug fixed until then.

**Comment by matteobruni** [comment] 2021-05-10 10:27
I think it’s possible. I started a new feature but I splitted it from that branch so it can be released later.

**Closed as completed** 2021-05-11 10:49 UTC
Labels: bug, help wanted, good first issue, up-for-grabs, pinned
