### ISSUE TITLE
Is the Readme file for Angular outdated? Can't run it with latest Angular

### ISSUE THREAD

**Issue by nazrinnoorzan** [tsparticles/tsparticles#2574] opened 2021-11-23 07:17 UTC
### Contact Details

nazrinnoorzan@gmail.com

### What do you need?

I just created a new Angular project and based on this Angular readme https://github.com/matteobruni/tsparticles/blob/main/components/angular/README.md , I can't compile and run the project. 

Here's my app.component.html, app.module.ts & app.component.ts files

app.component.html
`<ng-particles [id]="id" [options]="particlesOptions" (particlesInit)="particlesInit($event)"></ng-particles>`

app.component.ts
```
import { Component } from '@angular/core';
import { Main } from "tsparticles";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular-confetti';
  id = "tsparticles";

    particlesOptions = {
        background: {
            color: {
                value: "#0d47a1"
            }
        },
        fpsLimit: 60,
        interactivity: {
            events: {
                onClick: {
                    enable: true,
                    mode: "push"
                },
                onHover: {
                    enable: true,
                    mode: "repulse"
                },
                resize: true
            },
            modes: {
                bubble: {
                    distance: 400,
                    duration: 2,
                    opacity: 0.8,
                    size: 40
                },
                push: {
                    quantity: 4
                },
                repulse: {
                    distance: 200,
                    duration: 0.4
                }
            }
        },
        particles: {
            color: {
                value: "#ffffff"
            },
            links: {
                color: "#ffffff",
                distance: 150,
                enable: true,
                opacity: 0.5,
                width: 1
            },
            collisions: {
                enable: true
            },
            move: {
                direction: "none",
                enable: true,
                outMode: "bounce",
                random: false,
                speed: 6,
                straight: false
            },
            number: {
                density: {
                    enable: true,
                    value_area: 800
                },
                value: 80
            },
            opacity: {
                value: 0.5
            },
            shape: {
                type: "circle"
            },
            size: {
                random: true,
                value: 5
            }
        },
        detectRetina: true
    };
    
    particlesInit(main: Main): void {
        console.log(main);
    }
}
```

app.module.ts
```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { NgParticlesModule } from "ng-particles";

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule, NgParticlesModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Errors that I received when _**npm run start**_

```
Error: src/app/app.component.html:1:26 - error TS2322: Type '{ background: { color: { value: string; }; }; fpsLimit: number; interactivity: { events: { onClick: { enable: boolean; mode: string; }; onHover: { enable: boolean; mode: string; }; resize: boolean; }; modes: { ...; }; }; particles: { ...; }; detectRetina: boolean; }' is not assignable to type 'RecursivePartial<IOptions>'.
  The types of 'particles.move.outMode' are incompatible between these types.
    Type 'string' is not assignable to type '"none" | "bounce" | "destroy" | OutMode | "bounceHorizontal" | "bounceVertical" | "out" | "split" | OutModeAlt | undefined'.

1 <ng-particles [id]="id" [options]="particlesOptions" (particlesInit)="particlesInit($event)"></ng-particles>
                           ~~~~~~~

  src/app/app.component.ts:6:16
    6   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.




** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


× Failed to compile.
```

### Version

1.37.4

### Which library are you using?

Angular (ng-particles)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment] 2021-11-23 22:30
Hi @nazrinnoorzan,

I tried reproducing the issue in my demo app (`demo/angular` folder in this repository) and here on CodeSandbox (<https://codesandbox.io/s/frosty-ishizaka-1nm3c?file=/src/app/app.component.ts>) but the error wasn't returned.

The error is weird because `"bounce"` is part of `type '"none" | "bounce" | "destroy" | OutMode | "bounceHorizontal" | "bounceVertical" | "out" | "split" | OutModeAlt | undefined'`.

**Comment by nazrinnoorzan** [comment] 2021-11-24 01:48
I see. Can you try it with this package.json below?

```
{
  "name": "angular-confetti",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.0.0",
    "@angular/common": "~13.0.0",
    "@angular/compiler": "~13.0.0",
    "@angular/core": "~13.0.0",
    "@angular/forms": "~13.0.0",
    "@angular/platform-browser": "~13.0.0",
    "@angular/platform-browser-dynamic": "~13.0.0",
    "@angular/router": "~13.0.0",
    "ng-particles": "^2.20.4",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "tsparticles": "^1.37.4",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.0.3",
    "@angular/cli": "~13.0.3",
    "@angular/compiler-cli": "~13.0.0",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~3.10.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.4.3"
  }
}

```

**Comment by matteobruni** [comment] 2021-11-24 23:35
Ok I tested with Angular 13 and I got the error, It will be inspected soon. Anyway there's an easy workaround:

```
 particlesOptions: ISourceOptions = { // add the type to this variable, you can import this type from "tsparticles"
```

**Closed as completed** 2021-12-25 21:52 UTC
Labels: triage
