### ISSUE TITLE
Unable to Override Canvas Inline Style in tsparticle 2.9.3

### ISSUE THREAD

**Issue by amberyufangchiu** [tsparticles/tsparticles#4986] opened 2023-05-17 09:40 UTC
### Contact Details

amber.yufangchiu@gmail.com

### What do you need?

After updating tsparticle from version 1.19.4 to 2.9.3, I noticed that the inline style of the canvas element has changed. However, I am unable to override the new inline style using CSS or other methods.

I have attempted to use CSS overrides, inline styles, and JavaScript manipulation without success. The inline style seems to take precedence over any modifications I make.

New inline style:
<img width="867" alt="after" src="https://github.com/matteobruni/tsparticles/assets/58634677/c2e8b6dd-9d6b-4fe5-adaa-39ce64c69c97">

Old inline style (which I want it become):
<img width="873" alt="before" src="https://github.com/matteobruni/tsparticles/assets/58634677/6cd6fb24-8e0a-45e6-941d-e8c0c04dba47">

Versions:
tsparticle: 2.9.3
Previous tsparticle version: 1.19.4

I would appreciate any guidance or suggestions on how to override the inline style of the canvas element in tsparticle 2.9.3. Thank you!

### tsParticles Version

2.9.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment] 2023-05-17 09:49
Duplicate of #4872

**Closed as not planned by matteobruni** 2023-05-17 09:49 UTC
Labels: triage
