### ISSUE TITLE
[Bug]: change the background to a picture but it doesn't work

### ISSUE THREAD

**Issue by visualczm** [tsparticles/tsparticles#5316] opened 2024-03-03 02:48 UTC
### Contact Details

448443959@qq.com

### What happened?

```
<script src="https://cdn.jsdelivr.net/npm/@tsparticles/preset-fountain@3/tsparticles.preset.fountain.bundle.min.js"></script>
tsParticles.load({
  id: "tsparticles",
  options: {
    particles: {
      shape: {
        type: "square", // starting from v2, this require the square shape script
      },
    },
    preset: "fountain",
  },
});
```

I want to create a welcome effect for the company. I can set a background image and add text at the same time.

### tsParticles Version

CDN version3

### tsParticles Configuration

```json
const configs = { 
  id: "tsparticles",
options: 
{ 
  preset:"fountain",
  background: {
    image: "url('background3.jpg')",
    position: '50% 50%',
    repeat: 'no-repeat',
    size: 'cover',
    opacity: 1
  },
  particles: {
  opacity: {
    value: 1
},
}}}
```

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
The background image flashes and then disappears
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment] 2024-03-03 08:07
Duplicate of #4244

**Closed as not planned by matteobruni** 2024-03-03 08:07 UTC
Labels: bug, triage
