### ISSUE TITLE
Prevent particles from spawning automatically no longer works

### ISSUE THREAD

**Issue by vkaelin** [tsparticles/tsparticles#4905] opened 2023-02-12 11:54 UTC
### Contact Details

vkaelin@hey.com

### What do you need?

Hello, I saw your codepen to generate confetti on click: https://codepen.io/matteobruni/pen/wvPvOVg and it's exactly what I try to achieve: in your example, no particles are generating except the ones from the user clicks.

If I try to update the CDN version of `tsparticles` to 2.3.0+, it spawns as you can see here: (https://codepen.io/Kalane/pen/GRBVVwq) some particles automatically. I tried to play with all the options we have (`autoplay`, `particles.number.value`, ...) but I couldn't make it works.

Thanks a lot!

### tsParticles Version

2.3.0 to 2.9.1

### Which library are you using?

Vanilla (tsparticles), React.js (react-particles, react-tsparticles, react-particles-js)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment] 2023-02-12 12:08
Thanks for the report, I didn't notice this. I've found the first version with this issue, it's the `2.3.0`, this will help me find the issue. I'm preparing `2.9.2` and I will include this fix as well.

**Comment by vkaelin** [comment] 2023-02-12 12:15
Thanks a lot for the quick answer!

**Comment by matteobruni** [comment] 2023-02-12 12:56
`2.9.2` released with the fix

**Closed as completed** 2023-02-12 13:41 UTC
Labels: bug, help wanted, good first issue, up-for-grabs, plugin

**Comment by ludelafo** [comment] 2023-02-12 15:15
It seems the problem is the same with the Sea Anemone Preset. The animation starts right away.

Could this be related?

**Comment by matteobruni** [comment] 2023-02-12 15:29
> It seems the problem is the same with the Sea Anemone Preset. The animation starts right away.
> 
> Could this be related?

Sea Anemone config is made for starting it at the load, if you want to start it on click you can load it on your event. Otherwise you have to customize the configuration

**Comment by ludelafo** [comment] 2023-02-13 08:19
> Sea Anemone config is made for starting it at the load, if you want to start it on click you can load it on your event. Otherwise you have to customize the configuration

Got it, thank you very much!
