### ISSUE TITLE
A console.log has been forgotten

### ISSUE THREAD

**Issue by JustSxm** [tsparticles/tsparticles#3551] opened 2022-03-18 01:38 UTC
### Contact Details

reply to this thread

### What do you need?

A console.log was left in the Canvas, spamming the console when creating the particles at Canvas.js:236

### Version

1.42.2

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment] 2022-03-18 07:15
It's already fixed in #3528, it's not a spamming console.log since it's called once per instance.
I'm investigating #3523 and #3074 (the second is closed, but the issue is still present), then I'll release an update.

**Closed as completed** 2022-03-18 07:16 UTC
Labels: triage
